export const MOCK_CATEGORIES = [
  { id: 1, name: 'Văn học - Tiểu thuyết', slug: 'van-hoc', description: 'Các tác phẩm văn học kinh điển và đương đại' },
  { id: 2, name: 'Kinh tế - Khởi nghiệp', slug: 'kinh-te', description: 'Kiến thức kinh doanh, tài chính, đầu tư' },
  { id: 3, name: 'Tâm lý - Kỹ năng sống', slug: 'tam-ly-ky-nang', description: 'Phát triển bản thân, tư duy, tâm lý' },
  { id: 4, name: 'Khoa học - Lịch sử', slug: 'khoa-hoc-lich-su', description: 'Khám phá vũ trụ, tự nhiên, văn minh nhân loại' },
  { id: 5, name: 'Công nghệ - Lập trình', slug: 'cong-nghe', description: 'Sách chuyên môn công nghệ thông tin' },
  { id: 6, name: 'Thiếu nhi', slug: 'thieu-nhi', description: 'Truyện tranh, sách khám phá cho trẻ em' },
];

export const INITIAL_BOOKS = [
  {
    id: 1,
    title: 'Đắc Nhân Tâm (How to Win Friends and Influence People)',
    author: 'Dale Carnegie',
    publisher: 'NXB Tổng Hợp TP.HCM',
    publicationYear: 2021,
    isbn: '9786045890211',
    price: 88000,
    discountPrice: 66000,
    stockQuantity: 45,
    coverImageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80',
    pageCount: 320,
    language: 'Tiếng Việt',
    averageRating: 4.8,
    totalReviews: 128,
    active: true,
    isFeatured: true,
    category: MOCK_CATEGORIES[2],
    description: 'Đắc Nhân Tâm của Dale Carnegie là cuốn sách đưa ra những lời khuyên sâu sắc về cách ứng xử, giao tiếp và kết nối giữa người với người trong cuộc sống thường nhật cũng như trong công việc. Cuốn sách gối đầu giường của hàng triệu độc giả toàn cầu.',
  },
  {
    id: 2,
    title: 'Nhà Giả Kim (The Alchemist)',
    author: 'Paulo Coelho',
    publisher: 'NXB Hội Nhà Văn',
    publicationYear: 2020,
    isbn: '9786049890123',
    price: 79000,
    discountPrice: 59000,
    stockQuantity: 32,
    coverImageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&q=80',
    pageCount: 228,
    language: 'Tiếng Việt',
    averageRating: 4.9,
    totalReviews: 240,
    active: true,
    isFeatured: true,
    category: MOCK_CATEGORIES[0],
    description: 'Một câu chuyện ngụ ngôn tuyệt mỹ về hành trình đi tìm kho báu và sứ mệnh cuộc đời của chàng trai chăn cừu Santiago. Cuốn sách nhắc nhở chúng ta: "Khi bạn khao khát một điều gì đó, cả vũ trụ sẽ hợp lực giúp bạn đạt được nó."',
  },
  {
    id: 3,
    title: 'Atomic Habits - Thay Đổi Tí Hon, Hiệu Quả Bất Ngờ',
    author: 'James Clear',
    publisher: 'NXB Thế Giới',
    publicationYear: 2022,
    isbn: '9786047789012',
    price: 189000,
    discountPrice: 149000,
    stockQuantity: 28,
    coverImageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&q=80',
    pageCount: 380,
    language: 'Tiếng Việt',
    averageRating: 4.9,
    totalReviews: 95,
    active: true,
    isFeatured: true,
    category: MOCK_CATEGORIES[2],
    description: 'Atomic Habits tập trung vào quy luật 1% mỗi ngày. Không cần những nỗ lực phi thường, chỉ cần những thói quen nhỏ được lặp đi lặp lại có hệ thống, bạn sẽ tạo nên sự thay đổi khổng lồ trong sự nghiệp và đời sống.',
  },
  {
    id: 4,
    title: 'Sapiens: Lược Sử Loài Người',
    author: 'Yuval Noah Harari',
    publisher: 'NXB Tri Thức',
    publicationYear: 2021,
    isbn: '9786049448123',
    price: 230000,
    discountPrice: 185000,
    stockQuantity: 19,
    coverImageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80',
    pageCount: 560,
    language: 'Tiếng Việt',
    averageRating: 4.7,
    totalReviews: 87,
    active: true,
    isFeatured: true,
    category: MOCK_CATEGORIES[3],
    description: 'Từ một loài linh trưởng không nổi bật ở châu Phi, làm thế nào Homo Sapiens đã thống trị hành tinh này? Cuốn sách bao quát lịch sử loài người từ cuộc cách mạng nhận thức đến cách mạng công nghiệp.',
  },
  {
    id: 5,
    title: 'Clean Code: A Handbook of Agile Software Craftsmanship',
    author: 'Robert C. Martin',
    publisher: 'Prentice Hall',
    publicationYear: 2019,
    isbn: '9780132350884',
    price: 350000,
    discountPrice: 295000,
    stockQuantity: 15,
    coverImageUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e37b73?w=400&q=80',
    pageCount: 464,
    language: 'Tiếng Anh',
    averageRating: 4.8,
    totalReviews: 64,
    active: true,
    isFeatured: false,
    category: MOCK_CATEGORIES[4],
    description: 'Cuốn cẩm nang kinh điển của "Uncle Bob" dành cho lập trình viên muốn nâng tầm kỹ năng viết mã sạch, dễ bảo trì, dễ kiểm thử và chuẩn mực trong ngành công nghệ phần mềm.',
  },
  {
    id: 6,
    title: 'Cây Cam Ngọt Của Tôi',
    author: 'José Mauro de Vasconcelos',
    publisher: 'NXB Hội Nhà Văn',
    publicationYear: 2020,
    isbn: '9786049890456',
    price: 108000,
    discountPrice: 85000,
    stockQuantity: 40,
    coverImageUrl: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=400&q=80',
    pageCount: 244,
    language: 'Tiếng Việt',
    averageRating: 4.9,
    totalReviews: 310,
    active: true,
    isFeatured: true,
    category: MOCK_CATEGORIES[0],
    description: 'Tác phẩm tự truyện xúc động của nhà văn Brazil về cậu bé Zezé thông minh, nhạy cảm nhưng thiếu vắng tình yêu thương. Cuốn sách làm rung động hàng triệu trái tim về tình phụ tử và nỗi đau trưởng thành.',
  },
  {
    id: 7,
    title: 'Tư Duy Nhanh Và Chậm (Thinking, Fast and Slow)',
    author: 'Daniel Kahneman',
    publisher: 'NXB Thế Giới',
    publicationYear: 2021,
    isbn: '9786047789567',
    price: 249000,
    discountPrice: 199000,
    stockQuantity: 22,
    coverImageUrl: 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=400&q=80',
    pageCount: 612,
    language: 'Tiếng Việt',
    averageRating: 4.6,
    totalReviews: 53,
    active: true,
    isFeatured: false,
    category: MOCK_CATEGORIES[2],
    description: 'Tác phẩm đoạt giải Nobel kinh tế của Daniel Kahneman giải mã hai hệ thống tư duy chi phối mọi quyết định của con người: Hệ thống 1 (nhanh, bản năng, cảm tính) và Hệ thống 2 (chậm, logic, phân tích).',
  },
  {
    id: 8,
    title: 'Khởi Nghiệp Tinh Gọn (The Lean Startup)',
    author: 'Eric Ries',
    publisher: 'NXB Trẻ',
    publicationYear: 2020,
    isbn: '9786041189445',
    price: 145000,
    discountPrice: 116000,
    stockQuantity: 35,
    coverImageUrl: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400&q=80',
    pageCount: 360,
    language: 'Tiếng Việt',
    averageRating: 4.7,
    totalReviews: 76,
    active: true,
    isFeatured: true,
    category: MOCK_CATEGORIES[1],
    description: 'Phương pháp xây dựng doanh nghiệp và phát triển sản phẩm đột phá bằng cách thử nghiệm liên tục, thu thập phản hồi của khách hàng thật để tối ưu hóa nguồn lực và tránh lãng phí.',
  },
  {
    id: 9,
    title: 'Hoàng Tử Bé (Le Petit Prince)',
    author: 'Antoine de Saint-Exupéry',
    publisher: 'NXB Kim Đồng',
    publicationYear: 2022,
    isbn: '9786042256789',
    price: 65000,
    discountPrice: 52000,
    stockQuantity: 50,
    coverImageUrl: 'https://images.unsplash.com/photo-1524578271613-d550eacf6090?w=400&q=80',
    pageCount: 140,
    language: 'Tiếng Việt',
    averageRating: 4.9,
    totalReviews: 180,
    active: true,
    isFeatured: true,
    category: MOCK_CATEGORIES[5],
    description: '"Người ta chỉ thấy rõ với trái tim, điều cốt lõi vô hình trong mắt trần." Một kiệt tác văn học trường tồn về tình yêu, sự cô đơn và ý nghĩa của những điều giản dị nhất.',
  },
];

export const DEFAULT_MOCK_USERS = [
  {
    id: 1,
    username: 'admin',
    email: 'admin@bookrunner.vn',
    password: 'password123',
    fullName: 'Quản trị viên BookRunner',
    phone: '0901234567',
    address: '123 Trụ sở BookRunner, Quận 1, TP. Hồ Chí Minh',
    role: 'ROLE_ADMIN',
    enabled: true,
    createdAt: '2026-01-01T08:00:00',
  },
  {
    id: 2,
    username: 'customer',
    email: 'user@bookrunner.vn',
    password: 'password123',
    fullName: 'Nguyễn Văn An',
    phone: '0912345678',
    address: '456 Lê Lợi, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    role: 'ROLE_CUSTOMER',
    enabled: true,
    createdAt: '2026-02-15T09:30:00',
  },
];

export const INITIAL_ORDERS = [
  {
    id: 1,
    orderCode: 'BR-20260901-001',
    recipientName: 'Nguyễn Văn An',
    recipientPhone: '0912345678',
    shippingAddress: '456 Lê Lợi, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
    note: 'Giao giờ hành chính',
    totalAmount: 215000,
    shippingFee: 30000,
    finalAmount: 245000,
    status: 'DELIVERED',
    paymentMethod: 'COD',
    paymentStatus: 'PAID',
    createdAt: '2026-09-15T10:30:00',
    items: [
      {
        id: 101,
        quantity: 1,
        price: 66000,
        book: INITIAL_BOOKS[0],
      },
      {
        id: 102,
        quantity: 1,
        price: 149000,
        book: INITIAL_BOOKS[2],
      },
    ],
  },
];
